udo: required
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '6.2.0'

script: node_modules/karma/bin/karma start --browsers PhantomJS

before_deploy: npm run build:prod
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "cdn.hana053.com"
  skip_cleanup: true
  acl: public_read
  local_dir: dist
