udo: required
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '6.2.0'

install:
  - npm install
  # install aws cli
  - sudo apt-get -y install python-pip
  - sudo pip install awscli
  - aws --version

script: npm run sass && node_modules/karma/bin/karma start --browsers PhantomJS

after_success:
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  # Switch AWS Role when ENV is prod
  - test "${ENV}" = "prod" && source scripts/switch-production-role.sh

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: deploy/*
