udo: required
dist: trusty
language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
- '6.7.0'

before_install:
  - npm install -g yarn --cache-min 999999999
  - yarn --version
install:
  - yarn install

script: npm run sass && node_modules/karma/bin/karma start --browsers PhantomJS

before_deploy:
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  # install aws cli
  - sudo apt-get -y install python-pip curl
  - sudo pip install awscli
  - aws --version
deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: deploy/*
